### ISSUE TITLE
Feature Request - ixquick search engine

### ISSUE THREAD

**Issue by iembry** [coatless/searcher#6]
Will you consider adding ixquick (https://www.ixquick.com/) to your list of available search engines?

Thank you.

Irucka

**Comment by coatless** [comment]
@iembry yes. I'll add it to the list. 

I plan on introducing a way for users to specify their own search portals in the next release.

**Comment by iembry** [comment]
@coatless Ok, that will be great!

Thank you.

Irucka

**Comment by coatless** [comment]
Let’s leave this open so I remember to do it this weekend...

**Comment by coatless** [comment]
@iembry please give it a go on the dev version. This is about 1 month off from release.

```r
install.packages("devtools")
devtools::install_github("coatless/searcher")
```
